#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".



command="python git-tools/listDepRevs.py"
eval $command 
ret_code=$? 
if [ $ret_code == 0 ]; then
  git add .dep_revs
elif [ $ret_code != 1 ]; then
  # 1 means no dependency list was found, so nothing to do, but no error
  printf "Error : [%d] when trying to list this repo's dependencies" $ret_code 
  exit $ret_code 
fi 
